basePath: /
definitions:
  handler.CreateTransactionRequest:
    properties:
      amount:
        type: number
      credit_card_expires_month:
        type: integer
      credit_card_expires_year:
        type: integer
      credit_card_number:
        type: string
      credit_card_security_code:
        type: string
      name:
        type: string
    type: object
  handler.CreateTransactionResponse:
    properties:
      status:
        type: string
      uuid:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Fake Payment Gateway API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fake Payment Gateway API
  version: "1.0"
paths:
  /api/health-check:
    get:
      description: Verify health check application
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Health Check
      tags:
      - Health Check
  /api/v1/transactions:
    post:
      consumes:
      - application/json
      description: Create new transaction
      parameters:
      - description: New Transaction
        in: body
        name: new_task
        required: true
        schema:
          $ref: '#/definitions/handler.CreateTransactionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Create Transaction success
          schema:
            $ref: '#/definitions/handler.CreateTransactionResponse'
      security:
      - apiKey: []
      summary: Create Transaction
      tags:
      - Transaction
schemes:
- http
- https
securityDefinitions:
  apiKey:
    in: header
    name: access_token
    type: apiKey
swagger: "2.0"
